[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

# VeryChain Network Configuration
[rpc_endpoints]
verychain = "https://rpc.verylabs.io"

[etherscan]
verychain = { key = "${VERYSCAN_API_KEY}", url = "https://veryscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
