[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]
gas_limit = 30000000
gas_price = 20000000000

# VeryChain Network Configuration
[rpc_endpoints]
verychain = "https://rpc.verylabs.io"

[etherscan]
verychain = { key = "${VERYSCAN_API_KEY}", url = "https://veryscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


